from collections.abc import Sequence

from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "f7b8c9d0e1a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        "CREATE TABLE run_events ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE CASCADE, "
        "ts TIMESTAMPTZ NOT NULL DEFAULT now(), "
        "kind VARCHAR(64) NOT NULL, "
        "payload JSONB NOT NULL)"
    )
    op.execute("CREATE INDEX ix_run_events_run_id_id ON run_events (run_id, id)")


def downgrade() -> None:
    op.execute("DROP INDEX ix_run_events_run_id_id")
    op.execute("DROP TABLE run_events")
