from collections.abc import Sequence

from alembic import op

revision: str = "d8e9f0a1b2c3"
down_revision: str | None = "c7d8e9f0a1b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        "CREATE TABLE field_renames ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "field_id BIGINT NOT NULL REFERENCES fields(id) ON DELETE CASCADE, "
        "run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE CASCADE, "
        "agent_id BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE, "
        "previous_focus TEXT NOT NULL, "
        "new_focus TEXT NOT NULL, "
        "reason TEXT NOT NULL, "
        "verdict_on_previous TEXT NOT NULL, "
        "created_at TIMESTAMPTZ NOT NULL DEFAULT now()"
        ")"
    )
    op.execute(
        "CREATE INDEX ix_field_renames_field_created "
        "ON field_renames (field_id, created_at, id)"
    )
    op.execute("CREATE INDEX ix_field_renames_run ON field_renames (run_id)")


def downgrade() -> None:
    op.execute("DROP INDEX ix_field_renames_run")
    op.execute("DROP INDEX ix_field_renames_field_created")
    op.execute("DROP TABLE field_renames")
