from collections.abc import Sequence

from alembic import op

revision: str = "a7b8c9d0e1f2"
down_revision: str | None = "f0a1b2c3d4e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TABLE entries ADD COLUMN forced_reason TEXT")
    op.execute(
        """
        CREATE TABLE harness_notes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT REFERENCES runs(id) ON DELETE CASCADE,
            agent_id BIGINT REFERENCES agents(id) ON DELETE SET NULL,
            role VARCHAR(16),
            model VARCHAR(128),
            kind VARCHAR(16) NOT NULL,
            tool VARCHAR(64),
            text TEXT NOT NULL,
            meta JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_harness_notes_kind
                CHECK (kind IN ('bug', 'friction', 'missing', 'idea'))
        )
        """
    )
    op.execute("CREATE INDEX ix_harness_notes_run_id ON harness_notes (run_id, id)")
    op.execute("CREATE INDEX ix_harness_notes_tool_kind ON harness_notes (tool, kind)")


def downgrade() -> None:
    op.execute("DROP TABLE harness_notes")
    op.execute("ALTER TABLE entries DROP COLUMN forced_reason")
