from collections.abc import Sequence

from alembic import op

revision: str = "b8c9d0e1f2a3"
down_revision: str | None = "a7b8c9d0e1f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE entry_edits (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entry_id BIGINT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
            run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            agent_id BIGINT REFERENCES agents(id) ON DELETE SET NULL,
            reason TEXT NOT NULL,
            changes JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_entry_edits_entry ON entry_edits (entry_id, id)")


def downgrade() -> None:
    op.execute("DROP TABLE entry_edits")
